#!/usr/bin/env bash

set -e

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

apt-get update -q
apt-get install -q -y curl exuberant-ctags git-core ruby tmux vim wget
